### ISSUE TITLE
create an apk from fluent ui design kitchen sink

### ISSUE THREAD

**Issue by parth181195** [parth181195/fluent#9]
@ibhavikmakwana can u create a apk from fluent android library it will be ez to observe behaviour of some elements that way

**Comment by ibhavikmakwana** [comment]
Here it is.

[FluentUI.Demo-development-release.apk.zip](https://github.com/parth181195/fluent/files/6075688/FluentUI.Demo-development-release.apk.zip)

**Comment by parth181195** [comment]
Thanks 👍 clossing this for now
